### ISSUE TITLE
Uncaught TypeError: item.walk is not a function

### ISSUE THREAD

**Issue by GuillermoBaldan** [GuillermoBaldan/ZeroPlayers#35]
The console throws the following error:
```
Uncaught TypeError: item.walk is not a function
    at ZeroPlayers_f_matrixGeneration.js:167:26
    at Array.forEach (<anonymous>)
    at giveMovementToDynamicElements (ZeroPlayers_f_matrixGeneration.js:160:40)
    at matrixGenerator (ZeroPlayers_f_matrixGeneration.js:135:27)
    at continuosSimulationStep (ZeroPlayers_f_simulation.js:34:28)
    at simulation (ZeroPlayers_f_level1.js:56:3)
    at HTMLButtonElement.<anonymous> (ZeroPlayers_f_GUI.js:44:7)
```
This is the code:

```
function giveMovementToDynamicElements(matrix, stageParameters, simulationParameters) {
  let xy_before = [];
  let newPosition = [];
  let counter = 0;
  stageParameters.dynamicElementsArray.forEach((item) => {
/*     xy_before[0] = item.x
    xy_before[1] = item.y  */
    //1 Calculamos nueva posicióndo
    if (!(item.walkmode == "static")) { //If dynamic Elements are not static they can recive movement
      xy_before[0] = item.x
      xy_before[1] = item.y 
      newPosition = item.walk(item, stageParameters, simulationParameters);
 
      if ((newPosition[0] != xy_before[0]) || (newPosition[1] != xy_before[1])) {
       
        if (
          !forbiddenPosition(
            newPosition[0],
            newPosition[1],
            stageParameters,
            matrix
          )
        ) {//Actualizamos nueva posición
          
          item.x = newPosition[0];
          item.y = newPosition[1];
          matrix[item.y][item.x] = item.color;
       
          matrix[xy_before[1]][xy_before[0]] = stageParameters.staticStage[xy_before[1]][xy_before[0]];
        
        }
       }
    
 
    }
    
     //1.2 Comprobamos que no hay agua u otra célula en la nueva posición
   
  });

  return matrix;
}

```

It looks like the error is on this line:
`      newPosition = item.walk(item, stageParameters, simulationParameters);
`
I don't know how it is that now it gives me an error when it has been working.

**Comment by GuillermoBaldan** [comment]
Now it turns out that` item.walk = undefined`

**Comment by GuillermoBaldan** [comment]
The problem was this function:
```
function countingSpecies(name, stageParameters){
let i;
let flag = false;
let id;
for(i=0;i<stageParameters.dynamicElementsArray.length;i++){
  if(stageParameters.dynamicElementsArray[i].name==name){
    stageParameters.dynamicElementsArray[i].number++;
    id = `${name}_${stageParameters.dynamicElementsArray[i].number}`;
    flag = true;
  }
}
if (flag == false){
  stageParameters.dynamicElementsArray.push({name: name, number: 1});
  id = `${name}_1`;
}
```
I did this function to assing an Id to every cell, but it was getting a mistake.
