### ISSUE TITLE
Uncaught TypeError: item.walk is not a function

### ISSUE THREAD

**Issue by GuillermoBaldan** [GuillermoBaldan/ZeroPlayers#47]
I get this error again.
```
 at ZeroPlayers_f_matrixGeneration.js:239:24
    at Array.forEach (<anonymous>)
    at giveMovementToDynamicElementsv3 (ZeroPlayers_f_matrixGeneration.js:235:42)
    at matrixGenerator (ZeroPlayers_f_matrixGeneration.js:141:27)
    at continuosSimulationStep (ZeroPlayers_f_simulation.js:34:28)
    at simulation (ZeroPlayers_f_level1.js:60:3)
    at HTMLButtonElement.<anonymous> (ZeroPlayers_f_GUI.js:44:7)
    at HTMLButtonElement.<anonymous> (ZeroPlayers_f_GUI.js:112:47)
```

**Comment by GuillermoBaldan** [comment]
The script was capturing wrong values from the setting pannel. I´ve changed the html code:
```
<label for="movement">Movement</label>
                              <input type="radio" name="movement" value="Random">random
                          
                              <input type="radio" name="movement" value="path finder">path finder

                              <input type="radio" name="movement" value="None">None
                           </li>
                           <li>
                            <label for="initialNumber">Initial Number</label>
```
I rename "pathFinder" for "path finder" and "random" for "Random".
I´ve done this changes in order to have coincidence with the values of the class:
```
class genericLivingBeing {
    constructor(name, type, color, preys, movement, initialNumber) {
    this.name = name;
    //this.id = countingSpecies(this.name, stageParameters);
    this.type = type; //It can be "vegetable", "predator"
    this.color = color;
    this.preys = preys;
    this.movement = movement;
    this.initialNumber = initialNumber;
    this.x = Math.floor(
      Math.random() *
        (simulationParameters.wideDimension / simulationParameters.squareSide)
    ); //Math.random() * (max - min) + min;
    this.y = Math.floor(
      Math.random() *
        (simulationParameters.heightDimension / simulationParameters.squareSide)
    );
    if (movement == "None") {
    this.walkmode = "static";
    this.walk = "None";
    } else if (movement == "Random") {
      this.walkmode = "autonomous";
      this.walk = zigzagFreedom;
     } else if (movement == "path finder") {
      this.walkmode = "autonomous";
      this.walk = hunterGroupMovement;
     }

    this.trajectory_x = [1, 1, 1, 1, 1, 1, 1];
    this.trajectory_y = [0, 0, 0, 0, 0, 0, 0];
    this.life = 200;
    this.age = 0;
    this.maxEnergy = 250;
    this.energyBorn = this.maxEnergy / 2;
    this.energy = this.energyBorn;
    this.lifeConsumption = 1;
    this.energyConsumption = 1;
    this.behaviourRules = {
      forbiddenPositions: ["water", "simpleCell"],
      forbiddenColors: ["blue", "yellow", "purple"],
    };
    this.preys = preys;
    this.reproductionRadio = 1;
    this.reproductionPeriod = 4;
    this.cyclesToReproduction = Math.round(Math.random()*this.reproductionPeriod)
    this.vitalFunctions = {
      death: true,
      reproduction: false,
      prey: true,
      }
    this.cognitiveFunctions = {
      see: true,
      pathfinder: true,
    }
    
  }
}
```
