### ISSUE TITLE
Uncaught TypeError: item.preys.forEach is not a function

### ISSUE THREAD

**Issue by GuillermoBaldan** [GuillermoBaldan/ZeroPlayers#48]
I got this error from the console when putting the parameters througth the setting-panel.
Here you can see more details:
```
  at ZeroPlayers_f_livingbeings.js:179:16
    at Array.forEach (<anonymous>)
    at preyDetection (ZeroPlayers_f_livingbeings.js:178:40)
    at ZeroPlayers_f_livingbeings.js:334:29
    at Array.forEach (<anonymous>)
    at feeding (ZeroPlayers_f_livingbeings.js:324:40)
    at matrixGenerator (ZeroPlayers_f_matrixGeneration.js:143:2)
    at continuosSimulationStep (ZeroPlayers_f_simulation.js:34:28)
    at simulation (ZeroPlayers_f_level1.js:60:3)
    at HTMLButtonElement.<anonymous> (ZeroPlayers_f_GUI.js:44:7)
```

**Comment by GuillermoBaldan** [comment]
```
 let addThisSpeciesButton = document.getElementById("addThisSpecies").addEventListener(
    "click",
    function () {
  console.log(addThisSpeciesButton);
  let preys = [];
  let name = document.getElementById("speciesName").value;
  let type =  document.querySelector( 'input[name="speciesType"]:checked').value;
  let color = document.getElementById("color").value;
  preys.push(document.getElementById("preys").value);
  console.log("preys at addThisSpeciesButton: ");
  console.log(preys);
  let movement =  document.querySelector( 'input[name="movement"]:checked').value;
  let initialNumber = document.getElementById("initialNumber").value;
  initialNumber = parseInt(initialNumber);
  livingBeingsCollectionAux.push({
    name: name,
    type: type,
    color: color,
    preys: preys,
    movement: movement,
    number: initialNumber,
  });

  stageParameters.livingBeingsCollection = livingBeingsCollectionAux;
  console.log("livingBeingsCollection")
  console.log(stageParameters.livingBeingsCollection);
},
false
);
```

I´ve changed this line: `preys = preys.push(document.getElementById("preys").value);` for this other line:
`  preys.push(document.getElementById("preys").value);` and now it works well.
